#!/bin/bash

# iPhone 8+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D211" ]
then
  echo "D211 exists - iPhone 8+ Detected." 

mkdir "/Library/Application Support/11Cam16/D211BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist "/Library/Application Support/11Cam16/D211BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam16/D211/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D211/

else
   echo "D211 does not exists - Not an iPhone 8+."
fi


#iPhone X
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D221" ] 
then
    echo "D221 exists - iPhone X Detected." 

mkdir "/Library/Application Support/11Cam15/D221BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist "/Library/Application Support/11Cam16/D221BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam16/D221/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D221/

else
    echo "D221 does not exists - Not an iPhone X."
fi

echo "Flushing camera formats..."
rm -f /var/mobile/Library/Preferences/com.apple.cameracapture.volatile.plist

echo "Killing mediaserverd..."
killall mediaserverd || true
