#!/bin/bash

# iPhone 8+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D211" ] 
then
   echo "D211 exists - iPhone 8+ Detected." 

   rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist
   cp -R "/Library/Application Support/11Cam16/D211BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D211/
   rm -rf "/Library/Application Support/11Cam16/D211BAK/AVCaptureSession.plist"
   rm -rf "/Library/Application Support/11Cam16/D211BAK/"


else
   echo "Error: D211 does not exists."
fi
# iPhone X
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D221" ] 
then
    echo "D221 exists - iPhone X Detected." 

    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam16/D221BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D221/
    rm -rf "/Library/Application Support/11Cam16/D221BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam16/D221BAK/"

else
    echo "Error: D221 does not exists."
fi

rm -rf "/Library/Application Support/11Cam16/*"

echo "Flushing camera formats..."
rm -f /var/mobile/Library/Preferences/com.apple.cameracapture.volatile.plist

echo "Killing mediaserverd..."
killall mediaserverd || true
